---
# tasks file for Deploy-frontend
- name: Pull image from repository
  docker_image:
    name: 'namenge/ip2-client-img:v1.0.0'
    source: pull
- name: Create Node.js Backend Container
  docker_container:
    name: web-yolo-backend
    image: 'namenge/ip2-client-img:v1.0.0'
    networks:
      - name: app-net
    ports:
      - '3000:3000'
    command: npm start
  become: 'yes'
