apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-db
spec:
  selector:
    matchLabels:
      app: mongo-db
  serviceName: <ServiceName>
  replicas: 2
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
      - name: mongo-db-container
        image: namenge/mongo-db:mongo2024
        ports:
        - containerPort: 27017
          name: web
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
